name: Rsync Ansible files to controller 

on:
  push:
    branches: [ "main" ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Add controller SSH private key
        run: |
          mkdir -p ~/.ssh
          printf '%s' "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > ~/.ssh/controller.pem
          chmod 600 ~/.ssh/controller.pem

      - name: Trust server host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.ANSIBLE_HOST }}" >> ~/.ssh/known_hosts

      - name: Ensure target dir exists on server
        run: |
          ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -i ~/.ssh/controller.pem \
          "${{ secrets.EC2_USER }}@${{ secrets.ANSIBLE_HOST }}" \
            "mkdir -p /home/ubuntu/ansible"

      - name: Install ASG SSH key on controller
        run: |
          ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -i ~/.ssh/controller.pem \
          "${{ secrets.EC2_USER }}@${{ secrets.ANSIBLE_HOST }}" "
            mkdir -p ~/.ssh 
            chmod 700 ~/.ssh 
            echo '${{ secrets.ASG_SSH_KEY }}' > ~/.ssh/asg.pem 
            chmod 600 ~/.ssh/asg.pem
          "

      - name: Create a vault file and add secrets from aws and encrypt file (server pulls secrets from secret manager)
        env:
          SECRET_ID: ansible/vault_file_secrets
          AWS_REGION: us-east-1
        run: |
          ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -i ~/.ssh/controller.pem \
          "${{ secrets.EC2_USER }}@${{ secrets.ANSIBLE_HOST }}" \
          "SECRET_ID='${SECRET_ID}' AWS_REGION='${AWS_REGION}' bash -lc '
            cd ansible
            mkdir -p group_vars/all 

            aws secretsmanager get-secret-value \
              --secret-id "'"$SECRET_ID"'" \
              --region "'"$AWS_REGION"'" \
              --query SecretString --output text > ./group_vars/all/vault.yml

            cd group_vars/all
            ansible-vault encrypt vault.yml --vault-password-file /home/ubuntu/ansible/secrets_script.sh
          '"

      - name: Rsync only changed files to server
        run: |
          rsync -azP \
            --exclude-from='.gitignore' \
            -e "ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -i ~/.ssh/controller.pem" \
            ansible/ "${{ secrets.EC2_USER }}@${{ secrets.ANSIBLE_HOST }}:/home/ubuntu/ansible/"
