name: Rsync Ansible files 

on:
  push:
    branches: [ "main" ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code 
        uses: actions/checkout@v4

      - name: Add controller SSH private key
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > ~/.ssh/controller.pem
          chmod 600 ~/.ssh/controller.pem

      - name: Trust server host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.ANSIBLE_HOST }}" >> ~/.ssh/known_hosts

      - name: Ensure target dir exists on server
        run: |
          ssh -o IdentitiesOnly=yes -i ~/.ssh/controller.pem \
            ${{ secrets.EC2_USER }}@${{ secrets.ANSIBLE_HOST }} \
            "mkdir -p /home/ubuntu/projects/ansible"

      - name: Rsync only changed files to server
        run: |
          rsync -azP \
            --exclude-from='.gitignore' \
            -e "ssh -o IdentitiesOnly=yes -i ~/.ssh/controller.pem" \
            ansible/ ${{ secrets.EC2_USER }}@${{ secrets.ANSIBLE_HOST }}:/home/ubuntu/projects/ansible


            